# Change these first
owner: tapirs
repo: uptime

# Add your sites here
sites:
  - name: Tapirs
    url: https://www.tapirs.co.uk
  - name: Get-chips
    url: https://www.get-chips.co.uk

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.uptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://www.tapirs.co.uk/images/favicon-196x196.png
  name: Uptime
  introTitle: "**uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/uptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/uptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# uptime also supports notifications, assigning issues, and more
# See https://uptime.js.org/docs/configuration
